# Website settings 
url: "http://hemmelig.github.io"

# Internal nav
nav:
  main:
    research: "/research"

# Bio settings
name: "Conor Bacon"
description: "The home page of Conor Bacon, post-doctoral research associate at Columbia University"
website_repo_url: "https://github.com/hemmelig/conor-bacon-homepage"

# URLs
contact_urls:
  twitter:
    url: "https://twitter.com/Conor__Bacon"
    label: "Twitter"
    icon: "twitter-square"
    username: "@Conor__Bacon"
  github:
    url: "https://github.com/hemmelig"
    label: "GitHub"
    icon: "github-square"

# # Jekyll build settings
# paginate: 10
# paginate_path: "/writing/page:num"
# permalink: "/writing/:year/:month/:day/:title/"
# repository: hemmelig/conor-bacon-homepage

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
