# Website settings 
url: "http://hemmelig.github.io"

# Internal nav
nav:
  main:
    research: "/research"
    software: "/software"
    maps: "/maps"

# Bio settings
name: "Conor Bacon"
description: "The home page of Conor Bacon, post-doctoral research scientist at Columbia University"
website_repo_url: "https://github.com/hemmelig/hemmelig.github.io"

# URLs
contact_urls:
  twitter:
    url: "https://twitter.com/Conor__Bacon"
    label: "Twitter"
    icon: "twitter-square"
    username: "@Conor__Bacon"
  github:
    url: "https://github.com/hemmelig"
    label: "GitHub"
    icon: "github-square"
  google-scholar:
    url: "https://scholar.google.com/citations?user=02Lc7pEAAAAJ"

# Read files
include:
  - _pages
  - files
exclude:
  - Gemfile
  - README.md
  - .gitignore
keep_files:
  - .git

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
